homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.home, name=''),
	path('Blog', views.blog, name='blog'),
	path('Blog_1', views.blog_1, name='blog_1'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
	return render(request, 'Home.html')
	
def blog(request):
	return render(request, 'Blog.html')

def blog_1(request):
	return render(request, 'Blog1.html')

homepage/templates/Blog.html
<!DOCTYPE html>
{% load static %}
<html>
	<header>
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
		<nav>
			<ul>
				<li><a href="{% url 'homepage:' %}">Home</a></li>
				<li style="float:right;"><a href="#">Blog</a></li>
			</ul> 
		</nav>
	</header>
	<body>
		<h1 id="myblog">My Blog</h1><br><br><br><br><br>
		<a href="{% url 'homepage:blog_1' %}"><div class="blog-div">
			<img class="blog-img" src="{% static 'images/onizuka.jpg' %}" alt="first blog">
			<h2 class="blog-h2">First Blog - why</h2>
			<p class="blog-p">
Selamat PAGI!. kurang semangat, selamat pagi, siang, sore, atau malam teman-teman. Selamat datang di blog pertama saya, blog ini saya harap nantinya dapat bermanfaat bagi teman-teman, keluarga, pacar, gebetan, temennya pacar, pacarnya temen, rakyat indonesia, negara dll. Latar belakang dibuat nya blog ini karena belakangan ini saya sadar bahwa banyak kegiatan yang saya lakukan akan bermanfaat jika di sharing kepada orang lain. Misalnya kegiatan yang saya lakukan ketika liburan yaitu membuat sim (TANPA NEMBAK!), saya yakin jika saya menceritakan ke teman semua bisa lebih bermanfaat daripada hanya menjadi memori. Karena itu lahirlah blog ini yang nantinya akan menceritakan kegiatan yang saya mau ceritakan, ilmu/artikel/gambar yang saya tertarik untuk sebarkan entah karena lucu, bermanfaat maupun lainny. Sekian untuk tulisan kali ini. sampai bertemu lain waktu.<br><br><br>

Btw saya bukan wibu, itu background kebetulan aja belakangan ini lagi nonton anime itu. Nama anime nya "Great Teacher Onizuka". Anime ini bagus banget mengajarkan banyak nilai kehidupan seperti "jadi diri sendiri","sederhana","kebaikan" dll. tapi rating nya dewasa jadi untuk teman-teman yang masih ingusan tolong di lap dulu, ini anime untuk orang dewasa (sebenernya cuma ecchi sih).
			</p>
		</div></a>
		
	</body>
	<footer>
		<p>Reach me on : </p><br>
		
		<a href="https://steamcommunity.com/id/Newbie_Electric"><img id="footer_icon_1" src="{% static 'images/icon-steam.png' %}" alt="icon_steam"></a>
		<a href="https://www.instagram.com/irfanmaulananasution/"><img id="footer_icon_2" src="{% static 'images/icon-instagram.png' %}" alt="icon_instagram"></a>
		<a href="mailto:newbieelectric@gmail.com"><img id="footer_icon_3" src="{% static 'images/icon-email.png' %}" alt="icon_email"></a>
	</footer>
</html>

homepage/templates/Blog1.html
<!DOCTYPE html>
{% load static %}
<html>
	<header>
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
		<nav>
			<ul>
				<li><a href="{% url 'homepage:' %}">Home</a></li>
				<li style="float:right;"><a href="{% url 'homepage:blog' %}">Blog</a></li>
			</ul> 
		</nav>
	</header>
	<body>
		<h1 id="myblog">My Blog</h1><br><br><br><br><br>
		<div class="blog-div">
			<img class="blog-img" src="{% static 'images/onizuka.jpg' %}" alt="first blog">
			<h2 class="blog-h2">First Blog : why</h2>
			<p class="content-p">
Selamat PAGI!. kurang semangat, selamat pagi, siang, sore, atau malam teman-teman. Selamat datang di blog pertama saya, blog ini saya harap nantinya dapat bermanfaat bagi teman-teman, keluarga, pacar, gebetan, temennya pacar, pacarnya temen, rakyat indonesia, negara dll. Latar belakang dibuat nya blog ini karena belakangan ini saya sadar bahwa banyak kegiatan yang saya lakukan akan bermanfaat jika di sharing kepada orang lain. Misalnya kegiatan yang saya lakukan ketika liburan yaitu membuat sim (TANPA NEMBAK!), saya yakin jika saya menceritakan ke teman semua bisa lebih bermanfaat daripada hanya menjadi memori. Karena itu lahirlah blog ini yang nantinya akan menceritakan kegiatan yang saya mau ceritakan, ilmu/artikel/gambar yang saya tertarik untuk sebarkan entah karena lucu, bermanfaat maupun lainny. Sekian untuk tulisan kali ini. sampai bertemu lain waktu.<br>
<br>
Btw saya bukan wibu, itu background kebetulan aja belakangan ini lagi nonton anime itu. Nama anime nya "Great Teacher Onizuka". Anime ini bagus banget mengajarkan banyak nilai kehidupan seperti "jadi diri sendiri","sederhana","kebaikan" dll. tapi rating nya dewasa jadi untuk teman-teman yang masih ingusan tolong di lap dulu, ini anime untuk orang dewasa (sebenernya cuma ecchi sih).
			</p>
		</div>
		
	</body>
	<footer>
		<p>Reach me on : </p><br>
		
		<a href="https://steamcommunity.com/id/Newbie_Electric"><img id="footer_icon_1" src="{% static 'images/icon-steam.png' %}" alt="icon_steam"></a>
		<a href="https://www.instagram.com/irfanmaulananasution/"><img id="footer_icon_2" src="{% static 'images/icon-instagram.png' %}" alt="icon_instagram"></a>
		<a href="mailto:newbieelectric@gmail.com"><img id="footer_icon_3" src="{% static 'images/icon-email.png' %}" alt="icon_email"></a>
	</footer>
</html>

homepage/templates/Home.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
	</head>
	<body>
		<nav>
			<ul>
				<li><a href="#section-home">Home</a></li>
				<li style="float:right"><a href="{% url 'homepage:blog' %}">Blog</a></li>
			</ul> 
		</nav>
		
		<section id="section-home">
		<br>
			<img id="home_image" src="{% static 'images/home.png' %}" alt="home">
		</section>
		
		<section>
			<h1 class="title" id="about">About</h1>
			<p class="content">Born in Jakarta with Batak bloods, spent childhood in Bekasi. Spent first year of junior highschool in Sukabumi, spent the rest of teen hood in Surabaya. But Definitely 100% Indonesian. Currently giving thought to happiness, life purpose, the meaning of life, and the creation of the heavens and the earth</p>
			<img id="foto-profil" src="{% static 'images/ROKET.jpeg' %}" alt="irfan">
		</section>
		
		<section>
			<h1 class="title" id="education">Education</h1>
			<p class="content">
				<b>Universitas Indonesia (2018 – Present)</b><br>
				Computer Science Undergraduate Student<br><br>
				<b>SMA Al-Muslim Sidoarjo (2015 – 2018)</b><br><br>
				<b>SMP Al-Muslim Sidoarjo (2013 – 2015)</b><br><br>
				<b>SMP Al-A’raf BS Sukabumi (2012 – 2013)</b><br><br>
				<b>SDIT Al-Ishmah Bekasi (2008 – 2012)</b><br><br>
				<b>SD Al-Fikri Bekasi (2006 – 2008)</b><br><br>
			</p>
		</section>
		
		<section>
			<h1 class="title" id="experience">Experience</h1>
			<p class="content">
				<img class="logo" src="{% static 'images/logo_ristek.jpg' %}" alt="logo_ristek">
				<b>RISTEK (2019 – Present)</b><br>
				Junior Member Network Security & Operating System<br><br>
				<img class="logo" src="{% static 'images/logo_toastmaster.png' %}" alt="logo_toastmaster">
				<b>TOASTMASTER (2018 – Present)</b><br>
				Member in persuasive influence path Level (3/5)<br><br>
				<img class="logo" src="{% static 'images/logo_AIESEC.png' %}" alt="logo_AIESEC">
				<b>AIESEC (2018 – Present)</b><br>
				Organizing Committee Vice President of Partnership in Jakarta Environment Care Project Summer 2019<br><br>
				<img class="logo" src="{% static 'images/logo_steam.png' %}" alt="logo_steam">
				<b>Steam Trader (2015 – 2017)</b><br>
				Owner of newbie_electric account. Steam games and Dota 2 Item seller and trader
			</p>
		</section>
		
		<section>
			<h1 class="title" id="achievement">Achievement</h1>
			<p class="content">
				<b>Kompetisi Matematika Nalariah Realistik 2017</b><br>
				SMA – Nasional – Peraih medali PERUNGGU<br><br><br>

				<b>STATION – Statistics Competition 2016</b><br>
				SMA – Nasional – SEMI FINALIS<br><br><br>

				<b>Be Number One 2015</b><br>
				SMP – Kabupaten – Peraih JUARA 1

			</p>
		</section>
		
		<section>
			<h1 class="title" id="skill-title">Skill</h1>
			<h1 class="title" id="hobby-title">Hobby</h1>
			<p class="content" id="hobby-content">
				<b>Traveling  </b><img class="icon" src="{% static 'images/icon-travel.png' %}" alt="irfan"><br><br>
				<b>Music  </b><img class="icon" src="{% static 'images/icon-disc.png' %}" alt="irfan"><br><br>
				<b>Movie  </b><img class="icon" src="{% static 'images/icon-video.png' %}" alt="irfan"><br><br>
				<b>Sport  </b><img class="icon" src="{% static 'images/icon-tennis.png' %}" alt="irfan"><br>
			</p>
			<p class="content" id="skill-content">
				<img class="icon" src="{% static 'images/icon-language.png' %}" alt="icon-language"><b>  English as Second Language</b><br>
				<img class="icon" src="{% static 'images/icon-computer.png' %}" alt="icon-computing"><b>  Basic Computing Skill</b><br>
				<img class="icon" src="{% static 'images/icon-microphone.png' %}" alt="icon-publicSpeaking"><b>  Public Speaking</b><br>
				<img class="icon" src="{% static 'images/icon-js.png' %}" alt="irfan"><b>  Java Script</b><br>
				<img class="icon" src="{% static 'images/icon-python.png' %}" alt="irfan"><b>  Python</b><br>
				<img class="icon" src="{% static 'images/icon-html.png' %}" alt="irfan"><b>  HTML</b><br>
				<img class="icon" src="{% static 'images/icon-java.png' %}" alt="irfan"><b>  Java</b><br>
				<img class="icon" src="{% static 'images/icon-css.png' %}" alt="irfan"><b>  CSS</b>
			</p>
<!--maintenance	<h1 class="title" id="fact-title">who?what?</h1>
			<p class="content" style="top:-16%;">
				1.IM ESTJ-P<br>
				2. ? ? ?<br>
				3. ? ? ?<br>
				4. ? ? ?<br>
				5. ? ? ?<br>
				6. ? ? ?<br>
				7. ? ? ?<br>
			</p>
			<img class="photo" src="{% static 'images/BEFORE I DIE.jpg' %}" alt="photo1"><br>
			<img class="photo" src="{% static 'images/SMA.jpg' %}" alt="photo2">-->
		</section>
		<footer>
			<p>Reach me on : </p><br>
			
			<a href="https://steamcommunity.com/id/Newbie_Electric"><img id="footer_icon_1" src="{% static 'images/icon-steam.png' %}" alt="icon_steam"></a>
			<a href="https://www.instagram.com/irfanmaulananasution/"><img id="footer_icon_2" src="{% static 'images/icon-instagram.png' %}" alt="icon_instagram"></a>
			<a href="mailto:newbieelectric@gmail.com"><img id="footer_icon_3" src="{% static 'images/icon-email.png' %}" alt="icon_email"></a>
		</footer>
	</body>
</html>